version: "3"
services:
  dev:
    image: node:14
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run start
    ports:
      - 1234:1234
      - 1235:1235
  convergence:
    image: convergencelabs/convergence-omnibus
    expose:
      - "8000"
