version: "3.6"
services:
  server:
    build:
      context: .
      target: development
    command: ["npm", "run", "start:server"]
    container_name: server
    volumes:
      - "./src/server:/var/build/src/server"
      - "./src/shared:/var/build/src/shared"
  client:
    build:
      context: .
      target: development
    command: ["npm", "run", "start:client"]
    container_name: client
    ports:
      - "1234:1234"
      - "1235:1235"
    volumes:
      - "./src/client:/var/build/src/client"
      - "./src/shared:/var/build/src/shared"
  convergence:
    image: convergencelabs/convergence-omnibus
    ports:
      - "8000:8000"
    expose:
      - "8000"
