export const path = require('path');
export const ROOT = path.resolve(__dirname, '..');
export const SRC = path.join(ROOT, 'src');
export const DIST = path.join(ROOT, 'dist');
export const CLIENT_ROOT = path.join(SRC, 'client');
export const SHARED_ROOT = path.join(SRC, 'shared');
export const MONACO_ROOT = 'monaco-editor/esm/vs';
export const CLIENT_BUILD_PATH = path.join(ROOT, './bundle');
export const SERVER_BUILD_PATH = path.join(ROOT, './dist/server');
